FROM ubuntu:latest

MAINTAINER Your Name "your@email.com"

RUN apt-get update && apt-get install -y openjdk-8-jdk

WORKDIR /usr/local/bin/

ADD simple-service.jar .

ENTRYPOINT ["java", "-jar", "simple-service.jar"]